language: php

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

before_script:
  - composer install
  - composer dump-autoload

script:
  - vendor/bin/phpstan analyse -l max src --no-interaction --no-progress
  - vendor/bin/phpunit